[package]
name = "img"
version = "0.1.0"
edition = "2021"

[features]
default = ["qemu"]
qemu = []

[dependencies]
libparted = { git = "https://github.com/pop-os/libparted.git" }
log = "0.4.21"
tokio = "1.37.0"
serde_json = "1.0.115"

hub = { path = "../hub" }
async-trait = "0.1.79"